export const Strings = {
    linkHome : 'Inicio',
    linkShop : 'Productos',
    linkCart : 'Pedido',
    add2cart : 'El producto fue agregado al carrito!',
    ratings : 'Calificaciones',
    category : 'Categoría',
    add2cartBtn : 'Agregar al carrito',
    description : 'Descripción',
    reviews : 'Reseñas',
    visitCollection : 'Ver colleción',
    filterSelect : 'Filtrar por categoría',
    noItems : 'No hay artículos añadidos al carrito',
    cartSummary : 'Resumen del pedido',
    totalPrice : 'Precio total',
    alsoLike : 'También puede interesarte',
    ownerAddress : '3507 West Lawrence rd Phoenix Az 85019',
    ownerPhone : '+1 602-403-9778',
    helpPhone : '+1 602-775-3048',

}